apiVersion: hcp.hpe.com/v1
kind: Tenant
metadata:
  name: sampletenant
spec:
  clustername: dataplatform
  clustertype: external
  baseimagetag: "202103300853C"
  imageregistry: gcr.io/mapr-252711
  imagepullsecret: imagepull
  security:
    environmenttype: hcp
    usesssd: true
    externalusersecret: mapr-user-secrets
    externalconfigmap: mapr-external-cm
